// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Shared.Network;
using System.Collections.Generic;
using System;
using Shared.Network.Tables;

namespace Shared.Network
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<ClassRoomDefinition> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new ClassRoomDefinitionTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.GeneralConfigDefinitionTable
            
            );
        }

        public void RemoveClassRoomDefinition(string[] keys)
        {
            var data = RemoveCore(memory.ClassRoomDefinitionTable.GetRawDataUnsafe(), keys, x => x.Id, System.StringComparer.Ordinal);
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new ClassRoomDefinitionTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.GeneralConfigDefinitionTable
            
            );
        }

        public void Diff(ClassRoomDefinition[] addOrReplaceData)
        {
            var data = DiffCore(memory.ClassRoomDefinitionTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.StringComparer.Ordinal);
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new ClassRoomDefinitionTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.GeneralConfigDefinitionTable
            
            );
        }

        public void ReplaceAll(System.Collections.Generic.IList<GeneralConfigDefinition> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new GeneralConfigDefinitionTable(newData);
            memory = new MemoryDatabase(
                memory.ClassRoomDefinitionTable,
                table
            
            );
        }

        public void RemoveGeneralConfigDefinition(string[] keys)
        {
            var data = RemoveCore(memory.GeneralConfigDefinitionTable.GetRawDataUnsafe(), keys, x => x.Id, System.StringComparer.Ordinal);
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new GeneralConfigDefinitionTable(newData);
            memory = new MemoryDatabase(
                memory.ClassRoomDefinitionTable,
                table
            
            );
        }

        public void Diff(GeneralConfigDefinition[] addOrReplaceData)
        {
            var data = DiffCore(memory.GeneralConfigDefinitionTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.StringComparer.Ordinal);
            var newData = CloneAndSortBy(data, x => x.Id, System.StringComparer.Ordinal);
            var table = new GeneralConfigDefinitionTable(newData);
            memory = new MemoryDatabase(
                memory.ClassRoomDefinitionTable,
                table
            
            );
        }

    }
}